### ISSUE TITLE
remove legend(s)

### ISSUE THREAD

**Issue by AliciaSchep** [jonocarroll/ggeasy#3]
There are multiple ways to remove specific legends but it can be hard to remember and is frequently looked up on stackoverflow:

https://stackoverflow.com/questions/14604435/turning-off-some-legends-in-a-ggplot

```r
ggplot(mtcars, aes(wt, mpg, colour = cyl, size = hp)) +
  geom_point() + guides(size=FALSE)
```
and

```r
ggplot(mtcars, aes(wt, mpg, colour = cyl, size = hp)) +
  geom_point() + scale_size(guide = FALSE)
```

both work to remove just the size scale.

The idea here would be to add

```r
ggplot(mtcars, aes(wt, mpg, colour = cyl, size = hp)) +
  geom_point() + easy_remove_legend(size)
```

The `easy_remove_legend` function would take zero, one, or more names of legends to remove (e.g. fill, color, size, shape).  With zero, all legends would be removed (`theme(legend.position = "none")`).  

This would be easy to implement (and I am happy to do it myself), but perhaps removing legends isn't tricky enough for inclusion in this package -- thoughts?

**Comment by jonocarroll** [comment]
Perfect! I look this up myself plenty. Changing legend titles might be another one.

**Comment by AliciaSchep** [comment]
Great, I'll code this one up & make a PR.  Agree that changing legend titles could be a good one as well.  For testing, would the general approach be to just check that the function gives same object as the verbose ggplot method?  Or should we also bring in vdiffr for visual tests?

**Comment by jonocarroll** [comment]
This is solid work. I should have some time to add something in early next week. Keep adding any ideas you have into issues and I'll tackle some too.

**Comment by AliciaSchep** [comment]
Added in #5.  If we want to add function for changing legend titles or other legend manipulations (e.g. positioning or styling), those can be new issues.
