### ISSUE TITLE
Grid lines

### ISSUE THREAD

**Issue by jonocarroll** [jonocarroll/ggeasy#31]
> Removing minor axis lines!

 -- https://twitter.com/foundinblank/status/1202246795889455104?s=20

@foundinblank

**Comment by foundinblank** [comment]
Could be something like `easy_remove_gridlines(minor = TRUE, major = TRUE)`

**Comment by jonocarroll** [comment]
Which makes more sense to you?

`easy_remove_x_gridlines(minor = TRUE, major = TRUE)`

or 

`easy_remove_gridlines(minor_x = TRUE, major_x = TRUE)`

or 

`easy_remove_x_minor_gridlines()`

**Comment by foundinblank** [comment]
I'd err on the side of less functions with more parameters than more
functions w less parameters!

So:

`easy_remove_gridlines(minor_x = TRUE, minor_y = TRUE, major_x = TRUE,
major_y = TRUE)`

**Comment by thomas-neitmann** [comment]
My suggestion would be to have these three functions:

- `easy_remove_x_gridlines(major = TRUE, minor = TRUE)`
- `easy_remove_y_gridlines(major = TRUE, minor = TRUE)`
- `easy_remove_xy_gridlines(major = TRUE, minor = TRUE)` or alternatively `easy_remove_all_gridlines(major = TRUE, minor = TRUE)`

**Comment by jonocarroll** [comment]
Sounds good - I'm fine with having lots of functions/aliases so both `xy` and `all` are fine by me.

**Comment by thomas-neitmann** [comment]
Awesome! You'll get another pull request soon 😉

**Comment by jonocarroll** [comment]
Completed via #45

**Comment by foundinblank** [comment]
This is awesome :)
