### ISSUE TITLE
image links broken on ghpages

### ISSUE THREAD

**Issue by yonicd** [jonocarroll/ggeasy#41]
A lot of the image links are broken in the homepage of the site.

I think that `pkgdown` expects the outputs to be in `man/figures` (currently `fig.path = "tools/readme/README-"`) to copy them right for the site.

**Comment by jonocarroll** [comment]
Resolved in https://github.com/jonocarroll/ggeasy/commit/523856d89fb5b53af2627fe7b89e32b5528fd5d6, I hope.

**Comment by jonocarroll** [comment]
Thank you!
