### ISSUE TITLE
facets fail on polar coords above x number of rows

### ISSUE THREAD

**Issue by DataStrategist** [jonocarroll/ggeasy#50]
This code works:

```
library(tidyverse)
gapminder::gapminder %>% head(100) %>% 
  ggplot(aes(x = year, y = lifeExp)) + 
  geom_line() + coord_polar() +
  facet_wrap(~country) + theme_minimal() +
  ggeasy::easy_remove_axes()
```

but this fails to plot on my machine:
```
gapminder::gapminder %>% head(500) %>% 
  ggplot(aes(x = year, y = lifeExp)) + 
  geom_line() + coord_polar() +
  facet_wrap(~country) + theme_minimal() +
  ggeasy::easy_remove_axes()
```

The threshold seems to be exactly 200, but I have no idea why.

**Comment by jonocarroll** [comment]
Interesting... the plot doesn't seem to immediately appear when I try, but it doesn't fail. In RStudio (1.3.853) I can open the plot zoom panel and the plot *does* appear. Checking a reprex, it seems to work.

``` r
library(tidyverse)
gapminder::gapminder %>% head(500) %>% 
  ggplot(aes(x = year, y = lifeExp)) + 
  geom_line() + coord_polar() +
  facet_wrap(~country) + theme_minimal() +
  ggeasy::easy_remove_axes()
```

![](https://i.imgur.com/t5VUrjY.png)

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Are you getting an error?

**Comment by DataStrategist** [comment]
Exactly... it is strange... it DOESNT give an error, but it also doesn't execute in RStudio. Clearly there's no problem w/ your function... but what could it be?

**Comment by jonocarroll** [comment]
It may take a bit longer if the plot is slightly enlarged since there's no axis and it goes above the default 'window' size. It *does* execute for me in RStudio, it just takes a long time or I need to prod the window size by opening zoom or resizing the window. Glad to hear it's not an issue here, though. Cheers.
